ignore:
  - "**/persist-cli-tests"
  - "persist-cli/src/main/java/io/ballerina/persist/cmd/Push.java"
  - "persist-cli/src/main/java/io/ballerina/persist/utils/JdbcDriverLoader.java"
  - "persist-cli/src/main/java/io/ballerina/persist/utils/SqlScriptGenerationUtils.java"
  - "persist-cli/src/main/java/io/ballerina/persist/components/Enum.java"

coverage:
  precision: 2
  round: down
  range: "60...80"
  status:
    project:
      default:
        target: 80
