ignore:
  - "**/persist-cli-tests"
  - "persist-cli/src/main/java/io/ballerina/persist/components/Enum.java"
  - "persist-cli/src/main/java/io/ballerina/persist/PersistToolsConstants.java"

coverage:
  precision: 2
  round: down
  range: "60...80"
  status:
    project:
      default:
        target: 80
