fixes:
  - "ballerina/modules/types.duration/*::../ballerina/"
  - "ballerina/modules/types.struct/*::../ballerina/"
  - "ballerina/modules/types.timestamp/*::../ballerina/"
  - "ballerina/modules/types.wrappers/*::../ballerina/"

coverage:
  precision: 2
  round: down
  range: "60...80"
  status:
    project:
      default:
        target: 80
