ignore:
  - "tooling-tests"

fixes:
  - "native/src/main/java/io/ballerina/persist/*::/native/"

coverage:
  precision: 2
  round: down
  range: "60...80"
  status:
    project:
      default:
        target: 80
