[package]
org = "foo"
name = "medical_center"
version = "0.1.0"
distribution = "2201.4.0"

[build-options]
observabilityIncluded = false

[persist.entities.storage.mysql]
host = "localhost"
port = 3308
user = "root"
password = "Test123#"
database = "medical_center_db"

[persist]
datastore = "mysql"
module = "medical_center.entities"
